### ISSUE TITLE
An error occurs when inferencing

### ISSUE THREAD

**Issue by JiaySun1120** [hahminlew/easy-finetuning-stable-diffusion#1]
Thanks for sharing the great work! 
I tried to run the inference code while there was an error:

##OSError: hahminlew/sdxl-kream-model-lora-2.0 does not appear to have a file named pytorch_lora_weights.bin.##

I just wanted to know if you miss uploading some files to the huggingface repo. Thanks!

**Comment by hahminlew** [comment]
Sorry for the late response.
I've tested the colab demo today, and it works for me.
I think I did not miss any files to the huggingface repo.

However, I'm not sure which environments you are using for inference. Can you explain in more detail?
